<?php $txn = $this->getAttribute('txn'); ?>

<form action="/currency/txn/update/<?php echo $txn['id']; ?>/<?php echo $txn['currency_id']; ?>" method="post">
    <input name="id" type="hidden" value="<?php echo $txn['id']; ?>" />

    <label>Bought</label>
    <input name="bought" type="text" value="<?php echo $txn['bought']; ?>"/>

    <label>Spent ($)</label>
    <input name="spent" type="text" value="<?php echo $txn['spent']; ?>"/>

    <button>Update</button>

</form>